"""
KWLT Production Automation — Task Template Data

Python port of TaskTemplateData.gs. Master task lists for each production type.
"""

from typing import Optional

from app.constants import (
    ANCHOR_AUDITION_END,
    ANCHOR_AUDITION_START,
    ANCHOR_BUILD_POSSESSION,
    ANCHOR_CLOSING_NIGHT,
    ANCHOR_OPENING_NIGHT,
    ANCHOR_READTHROUGH,
    ANCHOR_TECH_WEEKEND_END,
    ANCHOR_TECH_WEEKEND_START,
    PRODUCTION_TYPE,
)


def get_task_template_for_type(production_type: Optional[str] = None) -> list[dict]:
    """
    Returns the task template data for a given production type.
    Port of getTaskTemplateForType() from TaskTemplateData.gs.
    """
    if production_type == PRODUCTION_TYPE.STUDIO_SERIES:
        return get_studio_series_task_template_data()
    return get_task_template_data()


def get_task_template_data() -> list[dict]:
    """Mainstage task template. Mirrors getTaskTemplateData() in Apps Script."""
    return [
        # ── Pre-Production Phase ───────────────────────────────────────────
        {
            "task": "Book extra audition days if needed with Rentals",
            "responsible": "Director",
            "generalRule": "1 month before auditions",
            "anchorRef": ANCHOR_AUDITION_START,
            "offsetDays": -30,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Pre-Production",
        },
        {
            "task": "Hold first Production meeting (invite Show Support Committee representative)",
            "responsible": "Production team",
            "generalRule": "1-2 months before auditions",
            "anchorRef": ANCHOR_AUDITION_START,
            "offsetDays": -45,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Pre-Production",
            "emailBody": "Hello,\n\nAs auditions approach for {{SHOW_NAME}}, this is a reminder to schedule your first production meeting and invite your Show Support Committee representative. If you have already had this meeting, please let the Show Support Committee know, as they have information to pass along.\n\nIf you have questions, please reach out to your Show Support representative.\n\n-- KWLT Show Support",
            "emailSubject": "[KWLT] First Production Meeting -- {{SHOW_NAME}}",
        },
        # ── Audition Preparation Phase ──────────────────────────────────────
        {
            "task": "Share resource folder and policies with production team",
            "responsible": "Show Support",
            "generalRule": "3 days before auditions",
            "anchorRef": ANCHOR_AUDITION_START,
            "offsetDays": -3,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Audition Prep",
            "autoComplete": True,
            "emailBody": "Hello,\n\nAuditions are fast approaching for {{SHOW_NAME}}! The production resources folder has been shared with you and can be found here:\n\n{{RESOURCES_URL}}\n\nMost importantly, please review the policy manual (available in the resources folder) before auditions, as there are several guidelines, deadlines, and rules that the production team will be expected to adhere to throughout the process.\n\nIf you have any questions, please reach out to your Show Support representative.\n\n-- KWLT Show Support",
            "emailSubject": "[KWLT] Resource Folder and Policies -- {{SHOW_NAME}}",
        },
        {
            "task": "Set up audition pre-booking form and confirmation/reminder system (if doing pre-bookings)",
            "responsible": "Stage Manager",
            "generalRule": "3 weeks before auditions",
            "anchorRef": ANCHOR_AUDITION_START,
            "offsetDays": -21,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Audition Prep",
        },
        {
            "task": "Create marketing materials for auditions",
            "responsible": "Producer",
            "generalRule": "3 weeks before auditions",
            "anchorRef": ANCHOR_AUDITION_START,
            "offsetDays": -21,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Audition Prep",
        },
        {
            "task": "Receive keys and get walkthrough of 44 Gaukel & 9 Princess",
            "responsible": "Stage Manager",
            "generalRule": "1 week before auditions",
            "anchorRef": ANCHOR_AUDITION_START,
            "offsetDays": -7,
            "notifyVia": "email",
            "recurring": False,
            "phase": "Audition Prep",
        },
        {
            "task": "Create rough marketing plan for the show and review with Communications Committee",
            "responsible": "Producer",
            "generalRule": "Deadline is auditions",
            "anchorRef": ANCHOR_AUDITION_START,
            "offsetDays": -7,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Audition Prep",
        },
        {
            "task": "Find audition wranglers",
            "responsible": "Production Team",
            "generalRule": "Deadline is auditions",
            "anchorRef": ANCHOR_AUDITION_START,
            "offsetDays": -7,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Audition Prep",
        },
        {
            "task": "Prepare in-audition materials (audition form, info sheets, printed monologues, scripts)",
            "responsible": "Stage Manager",
            "generalRule": "Deadline is auditions",
            "anchorRef": ANCHOR_AUDITION_START,
            "offsetDays": -3,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Audition Prep",
        },
        # ── Auditions & Casting Phase ───────────────────────────────────────
        {
            "task": "Obtain Vulnerable Sector Checks for show leadership (if minors in cast/crew)",
            "responsible": "Production team",
            "generalRule": "2 months before auditions",
            "anchorRef": ANCHOR_AUDITION_START,
            "offsetDays": -60,
            "notifyVia": "email",
            "recurring": False,
            "phase": "Auditions",
        },
        {
            "task": "IMPORTANT: Send acceptance and rejection notifications to ALL auditionees (required within 5 days per policy)",
            "responsible": "Director",
            "generalRule": "1 day after last day of auditions",
            "anchorRef": ANCHOR_AUDITION_END,
            "offsetDays": 1,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Auditions",
            "sendOnDate": True,
            "autoComplete": True,
            "emailBody": "Hello,\n\nAs auditions wrap up for {{SHOW_NAME}}, here are some important reminders about the casting process:\n\n1. Everyone who auditioned, regardless of whether they receive a role, must hear back about the result of their audition.\n2. Please encourage cast members not to announce their audition results until the cast list has been officially announced, to avoid hurt feelings.\n3. Please do not announce the cast list yourselves; KWLT shares it via official channels first. Once all the acceptances and rejections have gone out, please send the cast list to the Communications Committee (communications@kwlt.org).\n4. When scheduling the read-through, please invite the Show Support representative and Membership Director (membership@kwlt.org).\n\nMore detail around these rules can be found in the Policy Manual, under the Open Auditions Policy.\n\nIf you have any questions, please reach out to your Show Support representative.\n\n-- KWLT Show Support",
            "emailSubject": "[KWLT] Casting Reminders -- {{SHOW_NAME}}",
        },
        {
            "task": "Schedule rehearsals & readthrough (invite Show Support rep and Membership Director)",
            "responsible": "Stage Manager",
            "generalRule": "1 day after last day of auditions",
            "anchorRef": ANCHOR_AUDITION_END,
            "offsetDays": 1,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Auditions",
        },
        # ── Readthrough & Rehearsal Phase ───────────────────────────────────
        {
            "task": "Collect parental permission forms and emergency contact forms from cast & crew",
            "responsible": "Stage Manager",
            "generalRule": "At readthrough",
            "anchorRef": ANCHOR_READTHROUGH,
            "offsetDays": 0,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Rehearsals",
        },
        {
            "task": "Write press release and send to Communications Committee",
            "responsible": "Producer",
            "generalRule": "6 weeks before opening",
            "anchorRef": ANCHOR_OPENING_NIGHT,
            "offsetDays": -42,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Rehearsals",
        },
        {
            "task": "Submit poster for approval to Show Support representative",
            "responsible": "Producer",
            "generalRule": "6 weeks before opening (1 week before printing)",
            "anchorRef": ANCHOR_OPENING_NIGHT,
            "offsetDays": -42,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Rehearsals",
        },
        {
            "task": "Do headshots",
            "responsible": "Producer",
            "generalRule": "1 month before opening",
            "anchorRef": ANCHOR_OPENING_NIGHT,
            "offsetDays": -30,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Rehearsals",
        },
        {
            "task": "Do poster run around town",
            "responsible": "Producer",
            "generalRule": "1 month before opening",
            "anchorRef": ANCHOR_OPENING_NIGHT,
            "offsetDays": -30,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Rehearsals",
        },
        {
            "task": "Submit seating plan for approval to Show Support representative",
            "responsible": "Technical Director",
            "generalRule": "60 days after auditions",
            "anchorRef": ANCHOR_AUDITION_END,
            "offsetDays": 60,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Rehearsals",
        },
        {
            "task": "Collect information for program from cast & crew",
            "responsible": "Producer",
            "generalRule": "1 month before tech weekend",
            "anchorRef": ANCHOR_TECH_WEEKEND_START,
            "offsetDays": -30,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Rehearsals",
        },
        {
            "task": "Invite the board to your second dress rehearsal",
            "responsible": "Director",
            "generalRule": "2 weeks before opening",
            "anchorRef": ANCHOR_OPENING_NIGHT,
            "offsetDays": -14,
            "notifyVia": "email",
            "recurring": False,
            "phase": "Rehearsals",
        },
        # ── Build & Tech Phase ──────────────────────────────────────────────
        {
            "task": "Create program & get sign off from production",
            "responsible": "Producer",
            "generalRule": "Build weekend",
            "anchorRef": ANCHOR_BUILD_POSSESSION,
            "offsetDays": 0,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Build & Tech",
        },
        {
            "task": "Get safety training",
            "responsible": "Technical Director",
            "generalRule": "On possession",
            "anchorRef": ANCHOR_BUILD_POSSESSION,
            "offsetDays": 0,
            "notifyVia": "email",
            "recurring": False,
            "phase": "Build & Tech",
        },
        {
            "task": "Take possession of theatre",
            "responsible": "Production team",
            "generalRule": "1 week before possession",
            "anchorRef": ANCHOR_BUILD_POSSESSION,
            "offsetDays": -7,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Build & Tech",
            "autoComplete": True,
            "emailBody": "Hello,\n\nThe production team for {{SHOW_NAME}} is about to take possession of the theatre! Here are some important items:\n\nStrike Checklist: Please do a walkthrough with the checklist and inform the Show Support Committee of the current state of the theatre, so it can be noted before the post-show strike walkthrough.\n\nBuilding Responsibilities: Please review the attached document describing responsibilities for the building during the run.\n\nConcessions: Cast and crew purchases must be logged via the iPad at concessions using Square. Please share the concessions process with your cast and crew. The detailed process can be found in the resources folder.\n\nTech Weekend: The Show Support Committee will be dropping by on the morning of your tech Saturday. Please let them know what time you plan to begin.\n\nAll of these documents can be found in your production resources folder:\n{{RESOURCES_URL}}\n\nIf you have any questions, please reach out to your Show Support representative.\n\n-- KWLT Show Support",
            "emailSubject": "[KWLT] Theatre Possession -- {{SHOW_NAME}}",
        },
        {
            "task": "Walk through theatre with strike checklist and inform board of any problems",
            "responsible": "Stage Manager & Technical Director",
            "generalRule": "On possession",
            "anchorRef": ANCHOR_BUILD_POSSESSION,
            "offsetDays": 0,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Build & Tech",
        },
        {
            "task": "Plan tech weekend tasks",
            "responsible": "Production team",
            "generalRule": "Before tech weekend",
            "anchorRef": ANCHOR_TECH_WEEKEND_START,
            "offsetDays": -7,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Build & Tech",
        },
        {
            "task": "Invite Show Support committee representative to tech weekend Day 1",
            "responsible": "Stage Manager",
            "generalRule": "Start of first day of tech weekend",
            "anchorRef": ANCHOR_TECH_WEEKEND_START,
            "offsetDays": 0,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Build & Tech",
        },
        {
            "task": "Set sound & light cues",
            "responsible": "Technical Director",
            "generalRule": "Build week, due by tech weekend",
            "anchorRef": ANCHOR_TECH_WEEKEND_START,
            "offsetDays": 0,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Build & Tech",
        },
        {
            "task": "Remove everything from Gaukel",
            "responsible": "Production team",
            "generalRule": "By tech weekend",
            "anchorRef": ANCHOR_TECH_WEEKEND_START,
            "offsetDays": 0,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Build & Tech",
        },
        {
            "task": "Write front of house speech",
            "responsible": "Director",
            "generalRule": "Tech weekend",
            "anchorRef": ANCHOR_TECH_WEEKEND_END,
            "offsetDays": 0,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Build & Tech",
        },
        {
            "task": "Plan schedule for show nights",
            "responsible": "Production team",
            "generalRule": "By the end of tech weekend",
            "anchorRef": ANCHOR_TECH_WEEKEND_END,
            "offsetDays": 0,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Build & Tech",
        },
        {
            "task": "Run cue to cue",
            "responsible": "Stage Manager",
            "generalRule": "Tech weekend",
            "anchorRef": ANCHOR_TECH_WEEKEND_END,
            "offsetDays": 0,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Build & Tech",
        },
        {
            "task": "Print photos for lobby and programs",
            "responsible": "Producer",
            "generalRule": "After dress rehearsals, before opening",
            "anchorRef": ANCHOR_OPENING_NIGHT,
            "offsetDays": -3,
            "notifyVia": "slack",
            "recurring": False,
            "phase": "Build & Tech",
        },
        # ── Show Run Phase ──────────────────────────────────────────────────
        {
            "task": "Plan for strike",
            "responsible": "Stage Manager & Technical Director",
            "generalRule": "1 week before closing",
            "anchorRef": ANCHOR_CLOSING_NIGHT,
            "offsetDays": -7,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Shows",
            "emailBody": "Hello,\n\nClosing weekend is fast approaching for {{SHOW_NAME}}, which means strike is also coming up!\n\nThe strike checklist and strike policy can be found in your resources folder -- the checklist will help with strike, and the policy outlines expectations. As per the strike policy, board members will do a walkthrough of the theatre afterwards with the checklist and the evaluation will be passed along to the production team.\n\nIf there are any concerns about the state the theatre was received in that should be noted before this walkthrough (e.g., costumes or props left that are not the responsibility of this production), please let the Show Support Committee know.\n\nREMINDERS:\n\n- Props and Costumes: Now is a good time to organize what will happen to props and costumes. Any items to be donated to the theatre should be coordinated with the Props Manager (props@kwlt.org) and Costumes Manager (costumes@kwlt.org) BEFORE strike. No props should be left on shelves or costumes on the rack without explicit approval.\n\n- Alcohol Policy: No alcohol may be consumed on KWLT premises that has not been purchased from the bar and sold by a SmartServe Certified Volunteer. It is strongly recommended that no one participating in strike consume alcohol before strike begins. Alcohol for the strike party may be stored at the theatre during the show run, as long as it is out-of-sight and unopened.\n\nResources folder: {{RESOURCES_URL}}\n\nIf you have any questions or concerns, please reach out to your Show Support representative.\n\n-- KWLT Show Support",
            "emailSubject": "[KWLT] Strike Reminders -- {{SHOW_NAME}}",
        },
        # ── Post-Show Phase ─────────────────────────────────────────────────
        {
            "task": "Return keys",
            "responsible": "Production Team",
            "generalRule": "1 week after close",
            "anchorRef": ANCHOR_CLOSING_NIGHT,
            "offsetDays": 7,
            "notifyVia": "both",
            "recurring": False,
            "phase": "Post-Show",
        },
        {
            "task": "Submit receipts for reimbursement",
            "responsible": "Production Team",
            "generalRule": "Within 1 month of close",
            "anchorRef": ANCHOR_CLOSING_NIGHT,
            "offsetDays": 30,
            "notifyVia": "email",
            "recurring": False,
            "phase": "Post-Show",
        },
    ]


def get_studio_series_task_template_data() -> list[dict]:
    """Studio Series task template. Mirrors getStudioSeriesTaskTemplateData() in Apps Script."""
    PROD_MEETING_EMAIL_BODY = "Hello,\n\nAs auditions approach for {{SHOW_NAME}}, this is a reminder to schedule your first production meeting and invite your Show Support Committee representative. If you have already had this meeting, please let the Show Support Committee know, as they have information to pass along.\n\nIf you have questions, please reach out to your Show Support representative.\n\n-- KWLT Show Support"
    CASTING_EMAIL_BODY = "Hello,\n\nAs auditions wrap up for {{SHOW_NAME}}, here are some important reminders about the casting process:\n\n1. Everyone who auditioned, regardless of whether they receive a role, must hear back about the result of their audition.\n2. Please encourage cast members not to announce their audition results until the cast list has been officially announced, to avoid hurt feelings.\n3. Please do not announce the cast list yourselves; KWLT shares it via official channels first. Once all the acceptances and rejections have gone out, please send the cast list to the Communications Committee (communications@kwlt.org).\n4. When scheduling the read-through, please invite the Show Support representative and Membership Director (membership@kwlt.org).\n\nMore detail around these rules can be found in the Policy Manual, under the Open Auditions Policy.\n\nIf you have any questions, please reach out to your Show Support representative.\n\n-- KWLT Show Support"
    POSSESSION_EMAIL_BODY = "Hello,\n\nThe production team for {{SHOW_NAME}} is about to take possession of the theatre! Here are some important items:\n\nStrike Checklist: Please do a walkthrough with the checklist and inform the Show Support Committee of the current state of the theatre, so it can be noted before the post-show strike walkthrough.\n\nBuilding Responsibilities: Please review the attached document describing responsibilities for the building during the run.\n\nConcessions: Cast and crew purchases must be logged via the iPad at concessions using Square. Please share the concessions process with your cast and crew. The detailed process can be found in the resources folder.\n\nTech Weekend: The Show Support Committee will be dropping by on the morning of your tech Saturday. Please let them know what time you plan to begin.\n\nAll of these documents can be found in your production resources folder:\n{{RESOURCES_URL}}\n\nIf you have any questions, please reach out to your Show Support representative.\n\n-- KWLT Show Support"
    STRIKE_EMAIL_BODY = "Hello,\n\nClosing weekend is fast approaching for {{SHOW_NAME}}, which means strike is also coming up!\n\nThe strike checklist and strike policy can be found in your resources folder -- the checklist will help with strike, and the policy outlines expectations. As per the strike policy, board members will do a walkthrough of the theatre afterwards with the checklist and the evaluation will be passed along to the production team.\n\nIf there are any concerns about the state the theatre was received in that should be noted before this walkthrough (e.g., costumes or props left that are not the responsibility of this production), please let the Show Support Committee know.\n\nREMINDERS:\n\n- Props and Costumes: Now is a good time to organize what will happen to props and costumes. Any items to be donated to the theatre should be coordinated with the Props Manager (props@kwlt.org) and Costumes Manager (costumes@kwlt.org) BEFORE strike. No props should be left on shelves or costumes on the rack without explicit approval.\n\n- Alcohol Policy: No alcohol may be consumed on KWLT premises that has not been purchased from the bar and sold by a SmartServe Certified Volunteer. It is strongly recommended that no one participating in strike consume alcohol before strike begins. Alcohol for the strike party may be stored at the theatre during the show run, as long as it is out-of-sight and unopened.\n\nResources folder: {{RESOURCES_URL}}\n\nIf you have any questions or concerns, please reach out to your Show Support representative.\n\n-- KWLT Show Support"

    return [
        # Pre-Production
        {"task": "Book audition days with Rentals", "responsible": "Director", "generalRule": "1 month before auditions", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -30, "notifyVia": "slack", "recurring": False, "phase": "Pre-Production"},
        {"task": "Hold first Production meeting (invite Show Support Committee representative)", "responsible": "Production team", "generalRule": "1-2 months before auditions", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -45, "notifyVia": "both", "recurring": False, "phase": "Pre-Production", "emailBody": PROD_MEETING_EMAIL_BODY, "emailSubject": "[KWLT] First Production Meeting -- {{SHOW_NAME}}"},
        {"task": "Create plan for rehearsals (consider pre-scheduling all rehearsals for studio series)", "responsible": "Stage Manager and Director", "generalRule": "By the first production meeting", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -45, "notifyVia": "slack", "recurring": False, "phase": "Pre-Production"},
        {"task": "Create plan and deadlines for technical design elements", "responsible": "Stage Manager and Technical Director", "generalRule": "By the first production meeting", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -45, "notifyVia": "slack", "recurring": False, "phase": "Pre-Production"},
        # Audition Prep
        {"task": "Set up audition pre-booking form and confirmation/reminder system (if doing pre-bookings)", "responsible": "Stage Manager", "generalRule": "3 weeks before auditions", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -21, "notifyVia": "both", "recurring": False, "phase": "Audition Prep"},
        {"task": "Create marketing materials for auditions", "responsible": "Producer", "generalRule": "3 weeks before auditions", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -21, "notifyVia": "slack", "recurring": False, "phase": "Audition Prep"},
        {"task": "Decide on format for auditions", "responsible": "Director and Stage Manager", "generalRule": "By when audition form releases (3 weeks before auditions)", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -21, "notifyVia": "slack", "recurring": False, "phase": "Audition Prep"},
        {"task": "Schedule rehearsals & readthrough (invite Show Support rep and Membership Director)", "responsible": "Stage Manager", "generalRule": "By when audition form releases (can schedule before auditions for studio series)", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -19, "notifyVia": "both", "recurring": False, "phase": "Audition Prep"},
        {"task": "Receive keys and get walkthrough of 44 Gaukel & 9 Princess", "responsible": "Stage Manager", "generalRule": "1 week before auditions", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -7, "notifyVia": "email", "recurring": False, "phase": "Audition Prep"},
        {"task": "Create rough marketing plan for the show and review with Communications Committee", "responsible": "Producer", "generalRule": "Deadline is auditions", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -7, "notifyVia": "slack", "recurring": False, "phase": "Audition Prep"},
        {"task": "Find audition wranglers", "responsible": "Production Team", "generalRule": "Deadline is auditions", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -7, "notifyVia": "slack", "recurring": False, "phase": "Audition Prep"},
        {"task": "Prepare in-audition materials (audition form, info sheets, printed monologues, scripts)", "responsible": "Stage Manager", "generalRule": "Deadline is auditions", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -3, "notifyVia": "slack", "recurring": False, "phase": "Audition Prep"},
        # Auditions & Casting
        {"task": "Obtain Vulnerable Sector Checks for show leadership (if minors in cast/crew)", "responsible": "Production team", "generalRule": "ASAP, by last day of auditions", "anchorRef": ANCHOR_AUDITION_START, "offsetDays": -60, "notifyVia": "email", "recurring": False, "phase": "Auditions"},
        {"task": "IMPORTANT: Send acceptance and rejection notifications to ALL auditionees (required within 5 days per policy)", "responsible": "Director", "generalRule": "1 day after last day of auditions", "anchorRef": ANCHOR_AUDITION_END, "offsetDays": 1, "notifyVia": "both", "recurring": False, "phase": "Auditions", "sendOnDate": True, "autoComplete": True, "emailBody": CASTING_EMAIL_BODY, "emailSubject": "[KWLT] Casting Reminders -- {{SHOW_NAME}}"},
        # Rehearsals
        {"task": "Collect parental permission forms and emergency contact forms from cast & crew", "responsible": "Stage Manager", "generalRule": "At readthrough", "anchorRef": ANCHOR_READTHROUGH, "offsetDays": 0, "notifyVia": "both", "recurring": False, "phase": "Rehearsals"},
        {"task": "Select \"off book\" date (for 4-week rehearsal, off book should be 3rd week)", "responsible": "Stage Manager and Director", "generalRule": "By readthrough", "anchorRef": ANCHOR_READTHROUGH, "offsetDays": 0, "notifyVia": "slack", "recurring": False, "phase": "Rehearsals"},
        {"task": "Find photographer for headshots & dress rehearsal photos", "responsible": "Producer", "generalRule": "5 weeks before opening (optional for studio series)", "anchorRef": ANCHOR_OPENING_NIGHT, "offsetDays": -35, "notifyVia": "slack", "recurring": False, "phase": "Rehearsals", "optional": True},
        {"task": "Submit poster for approval to Show Support representative", "responsible": "Producer", "generalRule": "7 weeks before opening (optional for studio series)", "anchorRef": ANCHOR_OPENING_NIGHT, "offsetDays": -49, "notifyVia": "both", "recurring": False, "phase": "Rehearsals", "optional": True},
        {"task": "Print poster", "responsible": "Producer", "generalRule": "1 week before poster run (optional for studio series)", "anchorRef": ANCHOR_OPENING_NIGHT, "offsetDays": -37, "notifyVia": "slack", "recurring": False, "phase": "Rehearsals", "optional": True},
        {"task": "Collect information for program from cast & crew", "responsible": "Producer", "generalRule": "1 month before possession day", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": -30, "notifyVia": "slack", "recurring": False, "phase": "Rehearsals"},
        {"task": "Do headshots", "responsible": "Producer", "generalRule": "1 month before opening (optional for studio series \u2014 if doing, do at an early rehearsal)", "anchorRef": ANCHOR_OPENING_NIGHT, "offsetDays": -30, "notifyVia": "slack", "recurring": False, "phase": "Rehearsals", "optional": True},
        {"task": "Do poster run around town", "responsible": "Producer", "generalRule": "1 month before opening (optional for studio series)", "anchorRef": ANCHOR_OPENING_NIGHT, "offsetDays": -30, "notifyVia": "slack", "recurring": False, "phase": "Rehearsals", "optional": True},
        {"task": "Invite the board to your second dress rehearsal", "responsible": "Director", "generalRule": "2 weeks before opening", "anchorRef": ANCHOR_OPENING_NIGHT, "offsetDays": -14, "notifyVia": "email", "recurring": False, "phase": "Rehearsals"},
        # Build & Tech (single possession day)
        {"task": "Create program & get sign off from production", "responsible": "Producer", "generalRule": "Build weekend", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": 0, "notifyVia": "slack", "recurring": False, "phase": "Build & Tech"},
        {"task": "Get safety training", "responsible": "Technical Director", "generalRule": "On possession", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": 0, "notifyVia": "email", "recurring": False, "phase": "Build & Tech"},
        {"task": "Take possession & build your set", "responsible": "Production team", "generalRule": "Possession day", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": -3, "notifyVia": "both", "recurring": False, "phase": "Build & Tech", "autoComplete": True, "emailBody": POSSESSION_EMAIL_BODY, "emailSubject": "[KWLT] Theatre Possession -- {{SHOW_NAME}}"},
        {"task": "Walk through theatre with strike checklist and inform board of any problems", "responsible": "Stage Manager & Technical Director", "generalRule": "On possession", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": 0, "notifyVia": "both", "recurring": False, "phase": "Build & Tech"},
        {"task": "Plan tech/possession day tasks", "responsible": "Production team", "generalRule": "Before possession day", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": -7, "notifyVia": "slack", "recurring": False, "phase": "Build & Tech"},
        {"task": "Invite Show Support committee representative to possession day", "responsible": "Stage Manager", "generalRule": "1 week before possession day", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": -7, "notifyVia": "both", "recurring": False, "phase": "Build & Tech"},
        {"task": "Set sound & light cues", "responsible": "Technical Director", "generalRule": "Possession day", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": 0, "notifyVia": "slack", "recurring": False, "phase": "Build & Tech"},
        {"task": "Plan schedule for show nights", "responsible": "Production team", "generalRule": "Possession day", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": 0, "notifyVia": "slack", "recurring": False, "phase": "Build & Tech"},
        {"task": "Run cue to cue", "responsible": "Stage Manager", "generalRule": "Possession day", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": 0, "notifyVia": "slack", "recurring": False, "phase": "Build & Tech"},
        {"task": "Write front of house speech and send to show support for approval", "responsible": "Director", "generalRule": "Possession day", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": 0, "notifyVia": "both", "recurring": False, "phase": "Build & Tech"},
        {"task": "Print photos for lobby and programs", "responsible": "Producer", "generalRule": "Possession day, before opening", "anchorRef": ANCHOR_BUILD_POSSESSION, "offsetDays": 0, "notifyVia": "slack", "recurring": False, "phase": "Build & Tech"},
        # Shows
        {"task": "Plan for strike", "responsible": "Stage Manager & Technical Director", "generalRule": "1 week before closing", "anchorRef": ANCHOR_CLOSING_NIGHT, "offsetDays": -7, "notifyVia": "both", "recurring": False, "phase": "Shows", "emailBody": STRIKE_EMAIL_BODY, "emailSubject": "[KWLT] Strike Reminders -- {{SHOW_NAME}}"},
        # Post-Show
        {"task": "Return keys", "responsible": "Production Team", "generalRule": "1 week after close", "anchorRef": ANCHOR_CLOSING_NIGHT, "offsetDays": 7, "notifyVia": "both", "recurring": False, "phase": "Post-Show"},
        {"task": "Submit receipts for reimbursement", "responsible": "Production Team", "generalRule": "Within 1 month of close", "anchorRef": ANCHOR_CLOSING_NIGHT, "offsetDays": 30, "notifyVia": "email", "recurring": False, "phase": "Post-Show"},
    ]
